name: build for all platforms

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  build-all-for-all:
    runs-on: ubuntu-latest
    needs:
      - make-release
    strategy:
      matrix:
        os: [linux, freebsd]
        arch: [amd64, arm64]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - uses: actions/checkout@v3
      - if: matrix.arch == 'amd64'
        run: sudo apt update && sudo apt install -y --no-install-recommends musl-tools
      - if: matrix.arch == 'amd64'
        run: CC=$(which musl-gcc) GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags='-s -w -linkmode external -extldflags "-static"' -o ./trustedcoin
      - if: matrix.arch == 'arm64'
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags='-s -w' -o ./trustedcoin
      - run: tar -czf trustedcoin-${{ matrix.os }}-${{ matrix.arch }}.tar.gz trustedcoin
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: trustedcoin-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
